branches:
  only:
  - master
  - develop
  - "/^release\\/.*$/"
  - "/^hotfix\\/.*$/"
language: ruby
rvm:
- 2.3.0
env:
  matrix:
  - RAILS_ENV=development
  global:
  - secure: gzNKvP6X0+hRf97QQEf9TDrYDquR9WLjawvDkfQQrijKUrfnuWFb/upfj302djiXprVrW3vWDvwwvRMyg3mYCG4O1aJDrqNnkIsHHUbYCGpHw2Z4D4co/kzY2oTHc3PviP/toJz3Qig1kiOeVJ4uhaxpVvWDA8NT2Kef6KTZo8g= # AWS_BUCKET_ID_STAGING
  - secure: bPS1ACG3hz2ZJ3zrtcp0vQ1vbeLks4N5Kpyy4aFpdmgCdsmw9eVaMf0q3qjdHByvGe1Eq8TE2X5dgil7Rs+wakp8FfT72cHD/7SQXvUJjFcGSYkXs/e9A0TBsUgtfQQa95x3difYDgx5mYbm3v4Wi3TagMWsGi9YqKs5xbvsR1M=
  - secure: KPQlh2TS59uhZuJ2JMrsfc51LHllrNfnGJgjOxVGMBNW956Hs37v7n/+RQueMx6aznN1EGlJX4gYNlbD5jKWL6MZ4apkycYVO9/OtKg+0ByYqOXGtoMwYFCxtn3yrcTH0BpvuaCt1HiI+A2NGuqwgNJsZQ/XlgZAjbiDP7K2gNo=
  - secure: EJt3bnY4St7dgTnWYF8ZGj5a0UcC6XpYXBxiRq1Q9JiYAAHhFMsoP9w9eH4i4wiQahpm+hrTvX1mjF8bZEInKQ/RMF75hZ7Er+OWRPNtJr63RDoTDYLI2DTSimv/zoSDS59naQByhHGoPLfMlmr2qR9acpVzfcd0Jqnp7RyIB/M=
  - secure: RslcWlHJ/cbFMsHJFFWRfRNn/RqX4PuL+Zx+TckhjSMUSO6AvSE7WpMZcYVRQyOgrj086sAeDhlxotKDBJGOlQt53Kax9wrhGhBNNWQse9UFMDskjlEnL/RqPyTsTI1gViACyHuA9tAK/LbrL18gpJ4q8qGyL8zdahzTIWbbwtI= # AWS_BUCKET_ID_PRODUCTION
  - secure: RXp9v0s+ED4ISbM9zvT3X1hzNBRKLUreIJVmBdNKxgJzeeMZtiaTdlVLqRilnHWidMnhjV6yPNDMoYhDB9+85aBjxCQZ8+r/JrGE+cHgJ1CTRgswce1UhEndKWtNVZaMCWDI6NsNaAcSrrR69XgNh/JSsnZMvf0V8yeE3RmRbQo=
  - secure: Xm7/OVs6Sq6H4fmWwjDXZP0TLXqGGH7usTCll1IX+8GZZY64riibyRZIztf+t2IO8jg6KF+do2aZNbhnfBnli2j9U2KCNM0bOsHq3H/KmgwmA23pQbm9uwK5/6Ev098g6avGbRyUgOmpma4gVBy/fTaAPRrxFTheinr1cxygrdE=
  - secure: Qa0pgci1waMGWgKk6huekUJNzjd/X+xFuyXgGWMkgSR23exmJEOzfhkSgf/5thLJHYFwnuCoDKLFFT1NI9zvbhuLccjWCaApJmb3b9EJ/8bT2JosSQKXYFYZM6BwWIaV51w7C8Y0ayqhwu75v8tZzhe4adR7iY/+Ry8/sz73dSQ=
cache:
- apt
- bundler
after_success:
- if [[ "$TRAVIS_BRANCH" = "master" ]]; then export APP_ENV=production; fi
- if [[ "$TRAVIS_BRANCH" != "master" ]]; then export APP_ENV=staging; fi
- echo "BRANCH is $TRAVIS_BRANCH"
- echo "APP_ENV is $APP_ENV"
- echo "TRAVIS_PULL_REQUEST is $TRAVIS_PULL_REQUEST"
- bundle exec middleman build --verbose
- if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then bundle exec middleman s3_sync; fi
- if [[ "$TRAVIS_BRANCH" = "develop" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then bundle exec middleman s3_sync; fi
notifications:
  slack:
    secure: hl2m3ASUXdCDm3ztf9TYo05WtAvptI4Ql2tIP5UbOdGqG7eVSRcdd7RYwq7s1AHwlgkLs8BbqUQTcdTR9xRpzIH5RlYAv4kLIYKu7N6qnjdn6iN6ag7sC671I6AbfnA2sl4IKnomhEBW0n/NnBtQ+hm+UtTigXe8o2rprljhSOM=
